### ------- PROFILE page req and res check -------

### Get Header Details
GET http://localhost:3001/profile/headerDetails
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcxNDM0ODU0MiwiZXhwIjoxNzE0Mzc3MzQyfQ.jM0rE0NNuzKgOTeYzhQhOO1-b-WJ5QbI6HMc-VEWxCY

### Get Traveler Stats Details
GET http://localhost:3001/profile/travelerStats
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcxMzcyMTk1NSwiZXhwIjoxNzEzNzUwNzU1fQ.EimEBXTdMneJ9WUVd5mtXdMdrsxWC0LWcvcxt6McSdE

### GET User Details (To From Control)
GET http://localhost:3001/profile/getUserDetails
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcxMzk2NjI5MSwiZXhwIjoxNzEzOTk1MDkxfQ.2uJPochQTJuM0NdPzJELHHTRi_5f_MyewvzXX8tfurw


### Update User Details (From From Control)
POST http://localhost:3001/profile/saveNewUserDetails
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcxMzI2NjE3NywiZXhwIjoxNzEzMjY5Nzc3fQ.LWPO0s2mOFLvA6jF95t-hWiKiliLpp6qWN4eOoiI7uI

{
  "username":"123",
  "password":"123",
  "bio":"Bio 123"
}


### Update Travel Stats Details (Countries Visited)
POST http://localhost:3001/profile/countriesVisited
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImlhdCI6MTcxMzcyNDY3MSwiZXhwIjoxNzEzNzUzNDcxfQ.q18hphTCMkiFCmWUmjpOFdjbxtN-QKvRVhFeaSexUU0

{
  "countriesVisited":"2"
}



### Update Profile Pic
POST http://localhost:3001/profile/uploadProfilePic
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcxMzk2NjI5MSwiZXhwIjoxNzEzOTk1MDkxfQ.2uJPochQTJuM0NdPzJELHHTRi_5f_MyewvzXX8tfurw

{
  "profilePic":"2"
}